module.exports = {
    0: 'webserver unreachable',

    100: 'continue',
    101:  'switching protocols',

    200: '👌',
    201: 'created ok',
    202: 'request accepted ok',
    203: 'ok, non-authoritative information',
    204: 'ok, no content',
    205: 'ok, reset content',
    206: 'ok, partial content',

    300: 'multiple choices',
    301: 'the requested resource has moved permanently',
    302: 'the requested resource has moved temporarily',
    303: 'see other',
    304: 'the requested resource has not been modified since the last time you accessed it',
    305: 'use proxy',
    307: 'the requested resource has moved temporarily',
    308: 'the requested resource has moved permanently',

    400: 'bad request',
    401: 'unauthorised',
    402: 'payment required',
    403: 'forbidden',
    404: 'not found',
    405: 'method not allowed',
    406: 'unacceptable response',
    407: 'proxy authentication required',
    408: 'server timed out waiting for response',
    409: 'conflict',
    410: 'requested resource is gone permanently',
    411: 'length required',
    412: 'precondition failed',
    413: 'payload too large',
    414: 'uri too long',
    415: 'unsupported media type',
    416: 'range not satisfiable',
    417: 'expectation failed',
    426: 'upgrade required',
    429: 'too many requests',
    499: 'client closed the request before the server responded',

    500: 'internal server error',
    501: 'request not implemented',
    502: 'bad gateway - the server, acting as a gateway, received an invalid response from another server',
    503: 'service temporarily unavailable',
    504: 'the server, acting as a gateway, timed out waiting for another server to respond',
    505: 'http version not supported',
};
